### ISSUE TITLE
skd submit issues

### ISSUE THREAD

**Issue by bowenlee** [lithiumtech/lithium-sdk#15]
My Environment:
> OS : Ubuntu 14.04.1 LTS
>nodejs : vervison v0.12.5
>Npm : version 2.11.2
>Git : version 1.9.1
>gulp: version 3.9.0
>lithium-skd : version 0.0.5 

After <code> li submit-plugin</code>

It throws following errors in console
<pre>events.js:85</br>
      throw er; // Unhandled 'error' event</br>
            ^</br>
Error: read ECONNRESET</br>
    at exports._errnoException (util.js:746:11)</br>
    at TCP.onread (net.js:559:26)</br>
</pre>

**Comment by dougschroeder** [comment]
This is resolved in the current version of the SDK.
