### ISSUE TITLE
SDK version outdated in package.json

### ISSUE THREAD

**Issue by tylertadej** [lithiumtech/lithium-sdk#61]
Running the latest version of the SDK in a new project generates a package.json file with this:

```
  "devDependencies": {
    "lithium-sdk": "0.0.4"
  },
```

**Comment by iamkaran** [comment]
@dougschroeder  @chhamajain  @YuriKap  We can close this issue !

**Comment by dougschroeder** [comment]
Fix Version: 1.3.1
